export const environment = {
  production: false,
  oauthToken: 'Bearer BQDRXWhqZvfiYGehEghlSsIMYKo73waQujBDuBrkyJNnrVpdLXYCzopvUJloa8cwDUG5qZARf9yOpBVDdXVMpmVcgtGBu4e0ZwypQtbPU99mqvrT_R_66bKq1NA2SwmGhEaKvOO-rIH9ig0GNNZsyYkMlV5ESMWtR54URciLZrHFnxfgCsMd7B85VTvo5J9AMsM"'
};